# Generated by Django 4.2.9 on 2024-04-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_village",
            "0021_rename_close_re_object_reobjectinvillages_re_object_in_villages",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="web_page_link",
            field=models.TextField(
                blank=True,
                help_text="скопируйте ссылку iframe из браузера и вставьте в это поле",
                null=True,
                verbose_name="Ссылка на сайт послека",
            ),
        ),
    ]
