# Generated by Django 4.2.9 on 2024-04-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0022_village_web_page_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="web_page_link",
            field=models.TextField(
                blank=True,
                help_text="скопируйте ссылку из браузера и вставьте в это поле",
                null=True,
                verbose_name="Ссылка на сайт послека",
            ),
        ),
    ]
