# Generated by Django 4.2.9 on 2024-04-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_village", "0023_alter_village_web_page_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="village/pdf/", verbose_name="Буклет"
            ),
        ),
    ]
