version: "3.8"

services:
  backend: &django
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - infra/postgres/.env
    command: python manage.py runserver
    expose:
      - "8000"
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - media:/app/media
      - static:/app/staticroot
    networks:
      - real_estate_network


  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - '3000:3000'
    networks:
      - real_estate_network

  database:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    env_file:
      - infra/postgres/.env
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - real_estate_network

volumes:
  database_data:
    driver: local
networks:
  real_estate_network:
    driver: bridge