version: "3.8"

services:
  backend: &django
    build:
      context: .
      dockerfile: ./back/Dockerfile
    env_file:
      - infra/postgres/.env
    entrypoint: /usr/local/bin/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    # expose:
    #   - "8000"
    ports:
      - '8000:8000'
    volumes:
      - ./back:/app
      - media:/app/media
      - static:/app/staticroot
    networks:
      - real_estate_network


  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - '3000:3000'
    networks:
      - real_estate_network

  database:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    env_file:
      - infra/postgres/.env
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - real_estate_network

volumes:
  media:
    driver: local
  static:
    driver: local
  database_data:
    driver: local
networks:
  real_estate_network:
    driver: bridge