# Generated by Django 4.2.9 on 2024-04-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0060_reobjectclose"),
    ]

    operations = [
        migrations.AddField(
            model_name="reobject",
            name="isbook",
            field=models.BooleanField(
                blank=True, help_text="Да/Нет", null=True, verbose_name="Забронированно"
            ),
        ),
    ]
