# Generated by Django 4.2.9 on 2024-04-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reobjects", "0061_reobject_isbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="reobject",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="village/pdf/", verbose_name="Буклет"
            ),
        ),
    ]
