# Generated by Django 4.2.9 on 2024-04-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_reviews", "0005_rename_review_reviewimagemodel_objectmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="isAproove",
            field=models.BooleanField(
                blank=True,
                help_text="Да/Нет",
                null=True,
                verbose_name="Публикация на сайте",
            ),
        ),
    ]
